name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Setup Qt environment
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    - name: Run lrelease
      run: lrelease-pro pyqtpass.pro
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Windows32
        path: dist/
    - name: Rename to PyQtPass-32.exe
      run: mv dist/PyQtPass.exe dist/PyQtPass-32.exe
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass-32.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Setup Qt environment
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    - name: Run lrelease
      run: lrelease-pro pyqtpass.pro
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Windows64
        path: dist/
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        brew install create-dmg
    - name: Setup Qt environment
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    - name: Run lrelease
      run: lrelease-pro pyqtpass.pro
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Create DMG
      run: create-dmg dist/PyQtPass.dmg dist/PyQtPass.app
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-macOS
        path: dist/
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Setup Qt environment
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
    - name: Run lrelease
      run: lrelease-pro pyqtpass.pro
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Linux
        path: dist/
    - name: Rename to PyQtPass-linux
      run: mv dist/PyQtPass dist/PyQtPass-linux
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}