name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Windows
        path: dist/
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        brew install create-dmg
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Create DMG
      run: create-dmg dist/PyQtPass.app dist/PyQtPass.dmg
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Macos
        path: dist/
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller PyQtPass.spec
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PyQtPass-Linux
        path: dist/
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/PyQtPass
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}