name: Python Lint and Format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black

    - name: Run Pylint
      run: |
        # Run Pylint on all .py files in the directory
        pylint **/*.py

    - name: Check code formatting with Black
      run: |
        # Check if the codebase follows Black's style
        black --check .

